import { useCallback, useEffect, useState } from "react";
import { api } from "../../lib/api";
type File={id:string;name:string;webViewLink?:string;linked:boolean;linkedRecordId?:string};
export default function DriveInvoiceInbox({productionId,onReview}:{productionId:string;onReview:(file:File)=>void}) {
 const [data,setData]=useState<{files:File[];folderUrl:string|null;nextPageToken?:string;message?:string}>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async(token?:string)=>{setBusy(true);setError("");try{const next=await api.get<NonNullable<typeof data>>(`/api/project-finance/${productionId}/drive-inbox${token?`?pageToken=${encodeURIComponent(token)}`:""}`);setData(prev=>token&&prev?{...next,files:[...prev.files,...next.files]}:next);}catch(e){setError(e instanceof Error?e.message:"Could not read invoice folder.");}finally{setBusy(false);}},[productionId]);
 useEffect(()=>{load();const refresh=()=>{load();};window.addEventListener("focus",refresh);return()=>window.removeEventListener("focus",refresh);},[load]);
 return <div className="mb-6 rounded-lg border border-stone-200 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><h4 className="font-medium">From Google Drive</h4><p className="mt-1 text-xs text-stone-500">Drop invoices and credit notes into the Supplier invoices folder, then review them here. Choose the document type, supplier and amounts before saving a draft.</p></div><div className="flex gap-3 text-sm">{data?.folderUrl&&<a className="underline" href={data.folderUrl} target="_blank" rel="noreferrer">Open invoice folder</a>}<button className="underline" disabled={busy} onClick={()=>load()}>Refresh files</button></div></div>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{data?.message&&<p className="mt-3 text-sm text-stone-500">{data.message}</p>}<div className="mt-3 divide-y divide-stone-100">{data?.files.map(f=><div className="flex items-center justify-between gap-3 py-2 text-sm" key={f.id}><a className="truncate underline" href={f.webViewLink||`https://drive.google.com/file/d/${f.id}/view`} target="_blank" rel="noreferrer">{f.name}</a>{f.linked?<a className="shrink-0 text-xs text-emerald-700 underline" href={`#supplier-invoice-${f.linkedRecordId}`}>In register</a>:<button className="shrink-0 rounded border border-stone-200 px-3 py-2" onClick={()=>onReview(f)}>Review invoice</button>}</div>)}</div>{data?.folderUrl&&!data.files.length&&<p className="mt-3 text-sm text-stone-400">No documents in this folder yet.</p>}{data?.nextPageToken&&<button className="mt-3 text-sm underline" disabled={busy} onClick={()=>load(data.nextPageToken)}>Load more files</button>}</div>;
}
