import FxFields, { emptyFx, type FxValue } from "./FxFields";
import { useCallback, useEffect, useState } from "react";
import { api } from "../../lib/api";
import { Plus, Trash2, Copy, ExternalLink, RefreshCw } from "lucide-react";
type Line={fx?:FxValue|null;id?:string;description:string;qty:number|string;days:number|string;rate:number|string;plannedUnitCost:number|string|null;plannedSupplier:string|null};
type Section={id:string;name:string;lineItems:Line[]};
type Revision={id:string;revisionNumber:number;editVersion:number;isLocked:boolean;status:string;productionFeePercent:number|string;insurancePercent:number|string;sections:Section[];assumptions:string|null;paymentTerms:string|null;notes:string|null};
type Workspace={currency:string;project:{driveFolderId:string|null;driveSetupStatus:string;driveSetupError:string|null;estimateApprovals:{revisionNumber:number;clientTotalMinor:number}[]};revision:Revision;revisions:{id:string;revisionNumber:number;status:string}[]};
const button="inline-flex min-h-10 items-center justify-center gap-2 rounded-md border border-stone-200 bg-white px-3 py-2 text-sm hover:bg-stone-50 disabled:opacity-40";
const input="w-full min-w-0 rounded border border-stone-200 bg-white px-2 py-2 text-sm focus:border-emerald-600 focus:outline-none disabled:bg-stone-50";
const blank=():Line=>({description:"",qty:1,days:1,rate:0,plannedUnitCost:null,plannedSupplier:""});
export default function NewProjectEstimate({productionId,onApproved}:{productionId:string;onApproved:()=>void}) {
  const [data,setData]=useState<Workspace>();const [draft,setDraft]=useState<Revision>();const [history,setHistory]=useState<Revision[]>([]);
  const [fxRow,setFxRow]=useState<string>();
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [paste,setPaste]=useState("");const [confirm,setConfirm]=useState(false);
  const dirty=Boolean(draft&&data&&JSON.stringify(draft)!==JSON.stringify(data.revision));
  const load=useCallback(async()=>{const d=await api.get<Workspace>(`/api/project-workspace/${productionId}`);d.revision.sections.forEach(s=>s.lineItems.forEach(l=>{if(l.fx&&l.plannedUnitCost!==null&&l.plannedUnitCost!=="")l.plannedUnitCost=(l.fx.netMinor||0)/100;}));setData(d);let local:Revision|undefined;try{const cached=JSON.parse(sessionStorage.getItem(`estimate-draft:${productionId}`)||"null") as Revision|null;if(cached?.id===d.revision.id&&cached.editVersion===d.revision.editVersion&&!d.revision.isLocked)local=cached;}catch{/* Ignore unavailable browser storage. */}setDraft(local||structuredClone(d.revision));setHistory([]);},[productionId]);
  useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
  useEffect(()=>{if(!draft)return;try{if(dirty)sessionStorage.setItem(`estimate-draft:${productionId}`,JSON.stringify(draft));else sessionStorage.removeItem(`estimate-draft:${productionId}`);}catch{/* The unsaved-change indicator remains available. */}},[draft,dirty,productionId]);
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  useEffect(()=>{if(data?.project.driveSetupStatus!=="PENDING")return;const timer=setInterval(()=>{api.get<Workspace>(`/api/project-workspace/${productionId}`).then(d=>setData(prev=>prev?{...prev,project:d.project}:d)).catch(()=>{});},10000);return()=>clearInterval(timer);},[data?.project.driveSetupStatus,productionId]);
  function change(fn:(r:Revision)=>void){if(!draft)return;setHistory(h=>[...h.slice(-29),structuredClone(draft)]);const next=structuredClone(draft);fn(next);setDraft(next);setNotice("");}
  async function run(action:string){if(!draft)return;setBusy(true);setError("");setNotice("");try{await api.post(`/api/project-workspace/${productionId}/estimate/${action}`,{...draft,revisionId:draft.id});await load();setConfirm(false);if(action==="approve"){onApproved();}else setNotice(action==="save"?"Estimate saved.":"New draft created. The approved version is preserved.");}catch(e){setError(e instanceof Error?e.message:"Could not save estimate.");}finally{setBusy(false);}}
  async function exportPdf(revisionId:string){setBusy(true);setError("");try{const f=await api.post<{id:string;driveSyncStatus:string}>(`/api/project-workspace/${productionId}/export`,{revisionId});const download=document.createElement("a");download.href=`/api/files/${f.id}/download`;download.download="estimate.pdf";download.click();setNotice(f.driveSyncStatus==="PENDING"?"PDF created and queued for the project’s Client estimates folder. Track it in Files.":"PDF created. Open Files to publish it to Drive.");}catch(e){setError(e instanceof Error?e.message:"Export failed.");}finally{setBusy(false);}}
  if(!draft||!data)return <div className="p-8">{error?<p role="alert">{error} <button className={button} onClick={()=>load().catch(e=>setError(e.message))}>Retry</button></p>:"Loading estimate…"}</div>;
  const lines=draft.sections.flatMap(s=>s.lineItems);const subtotal=lines.reduce((sum,l)=>sum+Math.round(Number(l.qty)*Number(l.days)*Number(l.rate)*100),0);const fee=Math.round(subtotal*Number(draft.productionFeePercent)/100);const total=subtotal+fee+Math.round((subtotal+fee)*Number(draft.insurancePercent)/100);const planned=lines.reduce((sum,l)=>sum+Math.round(Number(l.qty)*Number(l.days)*Number(l.plannedUnitCost||0)*(l.fx&&l.fx.currency!==data.currency?Number(l.fx.rate)||0:1)*100),0);const missing=lines.filter(l=>Number(l.qty)*Number(l.days)>0&&(l.plannedUnitCost===null||l.plannedUnitCost==="")).length;
  const money=(n:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency:data.currency}).format(n/100);const disabled=busy||draft.isLocked;
  return <section className="mx-auto max-w-[1500px] space-y-5 p-4 md:p-8" aria-label="Project estimate">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-xl font-medium">Build your estimate</h3><p className="mt-1 text-sm text-stone-500">Version {draft.revisionNumber} · {draft.status.toLowerCase()} · {data.currency}{dirty?" · Unsaved changes":""}</p></div><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||dirty} onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={14}/>Refresh</button><button className={button} disabled={busy||!history.length||draft.isLocked} onClick={()=>{setDraft(history[history.length-1]);setHistory(h=>h.slice(0,-1));}}>Undo</button><button className={button} disabled={busy||dirty} onClick={()=>exportPdf(draft.id)}>Client PDF</button>{draft.isLocked?<button className={button} disabled={busy} onClick={()=>run("version")}>Start new version</button>:<><button className={`${button} !bg-stone-900 !text-white`} disabled={busy||!dirty} onClick={()=>run("save")}>{busy?"Saving…":"Save estimate"}</button><button className={button} disabled={busy||dirty} onClick={()=>setConfirm(true)}>Record client approval</button></>}</div></div>
    {error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="rounded bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-stone-200 bg-white p-4"><div className="text-sm"><strong>Project Drive</strong><p className="mt-1 text-stone-500">{data.project.driveSetupStatus==="READY"?"Brief, estimates, internal finance, supplier invoices and delivery folders are ready.":data.project.driveSetupStatus==="PENDING"?"Creating project folders… You can build the estimate while setup runs.":data.project.driveSetupError||"Drive folders have not been created yet."}</p></div>{data.project.driveFolderId?<a className={button} href={`https://drive.google.com/drive/folders/${data.project.driveFolderId}`} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Open project folder</a>:data.project.driveSetupStatus!=="PENDING"&&<button className={button} disabled={busy} onClick={async()=>{try{await api.post(`/api/project-workspace/${productionId}/retry-drive`,{});setData({...data,project:{...data.project,driveSetupStatus:"PENDING"}});}catch(e){setError(e instanceof Error?e.message:"Drive setup failed.");}}}>Set up Drive folders</button>}</div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Client estimate · net",money(total)],["Planned supplier cost",money(planned)],["Estimated margin",missing?"Complete planned costs":money(total-planned)],["Costs still to price",String(missing)]].map(([label,value])=><div key={label} className="rounded-lg border border-stone-200 bg-white p-4"><p className="text-xs text-stone-500">{label}</p><p className="mt-2 text-lg font-medium">{value}</p></div>)}</div>
    <p className="text-xs text-stone-500">Client rates appear on the estimate PDF. Planned rates, supplier names and internal notes stay in the app. Use the currency button on a row for foreign supplier rates. A blank planned rate means unpriced; enter 0 when there is no supplier cost.</p>
    {draft.sections.map((section,si)=><div key={section.id} className="rounded-lg border border-stone-200 bg-white"><div className="flex items-center justify-between gap-3 border-b border-stone-100 p-3"><input aria-label={`Section ${si+1} name`} className={`${input} max-w-md font-medium`} value={section.name} disabled={disabled} onChange={e=>change(r=>{r.sections[si].name=e.target.value;})}/><button className={button} disabled={disabled} onClick={()=>change(r=>{r.sections[si].lineItems.push(blank());})}><Plus size={14}/>Add line</button></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="text-xs text-stone-500"><tr>{["Description","Qty","Days","Client rate","Planned rate","Supplier","Client total",""] .map((h,i)=><th className="px-2 py-3 font-normal" key={i}>{h}</th>)}</tr></thead><tbody>{section.lineItems.map((l,li)=><tr key={l.id||`new-${li}`} className="border-t border-stone-100">{(["description","qty","days","rate","plannedUnitCost","plannedSupplier"] as const).map(k=><td key={k} className="p-2"><input aria-label={`${section.name} row ${li+1} ${k}`} className={`${input} ${k==="description"?"min-w-44":k==="plannedSupplier"?"min-w-32":"w-24"}`} type={k==="description"||k==="plannedSupplier"?"text":"number"} min="0" step="0.01" placeholder={k==="plannedUnitCost"?"Unpriced":""} title={k==="plannedUnitCost"?`Planned rate in ${l.fx?.currency||data.currency}`:undefined} value={l[k]??""} disabled={disabled} onChange={e=>change(r=>{r.sections[si].lineItems[li][k]=e.target.value;})}/></td>)}<td className="whitespace-nowrap p-2 tabular-nums">{money(Math.round(Number(l.qty)*Number(l.days)*Number(l.rate)*100))}</td><td className="p-2"><div className="flex gap-2"><button title="Duplicate line" aria-label={`Duplicate ${l.description||"line"}`} disabled={disabled} onClick={()=>change(r=>{r.sections[si].lineItems.splice(li+1,0,{...l,id:undefined});})}><Copy size={14}/></button><button type="button" disabled={disabled} className="text-xs underline" onClick={()=>setFxRow(`${si}:${li}`)} aria-label={`Currency for ${l.description||"line"}`}>{l.fx?.currency||data.currency}</button><button title="Remove line" aria-label={`Remove ${l.description||"line"}`} disabled={disabled} onClick={()=>change(r=>{r.sections[si].lineItems.splice(li,1);})}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!section.lineItems.length&&<p className="p-4 text-sm text-stone-400">Add a line or paste rows below.</p>}</div></div>)}
    {!draft.isLocked&&<details className="rounded-lg border border-stone-200 bg-white p-4"><summary className="cursor-pointer text-sm font-medium">Paste rows from a spreadsheet</summary><p className="mt-3 text-xs text-stone-500">Tab-separated columns: description, quantity, days, client rate, planned rate, supplier. No header. Rows are added to the last section; review before saving.</p><textarea aria-label="Spreadsheet rows" className={`${input} mt-3 h-24`} value={paste} onChange={e=>setPaste(e.target.value)}/><button className={`${button} mt-2`} disabled={busy||!paste.trim()} onClick={()=>{const rows=paste.trim().split(/\r?\n/).map(row=>{const [description,qty="1",days="1",rate="0",plannedUnitCost="",plannedSupplier=""]=row.split("\t");return {description,qty,days,rate,plannedUnitCost,plannedSupplier};});change(r=>{r.sections[r.sections.length-1].lineItems.push(...rows);});setPaste("");}}>Add pasted rows</button></details>}
    <div className="grid gap-4 rounded-lg border border-stone-200 bg-white p-4 md:grid-cols-2">{([['productionFeePercent','Production fee %'],['insurancePercent','Insurance %'],['assumptions','Client assumptions & scope'],['paymentTerms','Client payment terms'],['notes','Internal notes — excluded from client PDF']] as const).map(([k,label])=><label key={k} className="text-sm text-stone-600">{label}{k.endsWith('Percent')?<input className={`${input} mt-1`} type="number" min="0" max="100" step="0.01" value={draft[k]??""} disabled={disabled} onChange={e=>change(r=>{r[k]=e.target.value;})}/>:<textarea className={`${input} mt-1 min-h-24`} value={draft[k]??""} disabled={disabled} onChange={e=>change(r=>{r[k]=e.target.value;})}/>}</label>)}</div>
    <details className="text-sm"><summary className="cursor-pointer">Estimate version history ({data.revisions.length})</summary><div className="mt-3 space-y-2">{data.revisions.map(r=><div key={r.id} className="flex items-center justify-between rounded border border-stone-200 bg-white p-3"><span>Version {r.revisionNumber} · {r.status.toLowerCase()}</span><button className={button} disabled={busy||dirty} onClick={()=>exportPdf(r.id)}>Client PDF</button></div>)}</div></details>
    {fxRow&&(()=>{const [si,li]=fxRow.split(':').map(Number);const l=draft.sections[si]?.lineItems[li];if(!l)return null;return <div className="fixed inset-0 z-[801] grid place-items-center bg-black/30 p-4"><section role="dialog" aria-modal="true" aria-label="Planned supplier currency" className="w-full max-w-md rounded-lg bg-white p-5"><h3 className="mb-3 font-medium">{l.description}</h3><FxFields base={data.currency} value={l.fx||emptyFx(data.currency)} amount={String(l.plannedUnitCost||'')} onChange={fx=>change(r=>{r.sections[si].lineItems[li].fx=fx;})}/><p className="my-3 text-sm">The planned-rate cell uses this currency. Client rates remain {data.currency}.</p><button className={button} onClick={()=>setFxRow(undefined)}>Done</button></section></div>;})()}
    {confirm&&<div className="fixed inset-0 z-[800] grid place-items-center bg-black/30 p-4"><div role="dialog" aria-modal="true" aria-label="Record client approval" className="max-w-lg rounded-xl bg-white p-6 shadow-xl"><h3 className="text-lg font-medium">Record client approval</h3>{error&&<p role="alert" className="mt-3 text-sm text-red-800">{error}</p>}<p className="mt-3 text-sm text-stone-600">Confirm that the client approved version {draft.revisionNumber} for {money(total)} net. This freezes the estimate and adds new estimate lines to live costs as planned allowances. It does not book suppliers or send an email.</p>{data.project.estimateApprovals.length>0&&<p className="mt-3 text-sm text-amber-800">Existing live costs stay unchanged. Review any revised or removed allowances in Live costs after approval.</p>}<div className="mt-5 flex justify-end gap-2"><button className={button} disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button><button className={`${button} !bg-stone-900 !text-white`} disabled={busy} onClick={()=>run("approve")}>Confirm approval</button></div></div></div>}
  </section>;
}
