import { useEffect, useState } from "react";
import { api } from "../../lib/api";
type Review={checkedAt:string;currency:string;readyForFinalReview:boolean;drive:{complete:boolean;scannedFiles:number};items:{key:string;label:string;detail:string;view:string}[];summary:{approvedRevenueMinor:number|null;forecastCostMinor:number;expectedProfitMinor:number|null;clientReceivableMinor:number;supplierPayableMinor:number;supplierRefundDueMinor:number;clientRefundDueMinor:number}};
export default function ProjectReconciliation({productionId,refreshKey,onView}:{productionId:string;refreshKey:unknown;onView:(view:string)=>void}) {
 const [data,setData]=useState<Review>();const [error,setError]=useState("");const [attempt,setAttempt]=useState(0);const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError("");setData(undefined);api.get<Review>(`/api/project-finance/${productionId}/reconciliation`).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[productionId,refreshKey,attempt]);
 const money=(n:number|null)=>n===null?"No approval":new Intl.NumberFormat("en-GB",{style:"currency",currency:data?.currency||"GBP"}).format(n/100);
 return <div><div className="mb-4 flex flex-wrap justify-between gap-3"><div><h4 className="font-medium">Ready to close?</h4><p className="mt-1 text-sm text-stone-500">Review project finances and source documents before the final sign-off.</p></div><button className="rounded border border-stone-200 bg-white px-3 py-2 text-sm disabled:opacity-50" disabled={loading} onClick={()=>setAttempt(n=>n+1)}>Run checks again</button></div>{loading&&<p role="status" className="rounded bg-stone-50 p-4 text-sm">Checking balances and the project’s Drive invoice folder…</p>}{error&&<p role="alert" className="rounded bg-red-50 p-4 text-sm text-red-800">{error} The close check is incomplete.</p>}{data&&<><div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-3">{[["Approved revenue · net",data.summary.approvedRevenueMinor],["Forecast cost · net",data.summary.forecastCostMinor],["Expected profit · net",data.summary.expectedProfitMinor],["Client payments due",data.summary.clientReceivableMinor],["Supplier payments due",data.summary.supplierPayableMinor],["Supplier refunds due",data.summary.supplierRefundDueMinor],["Client refunds due",data.summary.clientRefundDueMinor]].map(([label,value])=><div key={String(label)} className="rounded-lg border border-stone-200 bg-white p-3"><p className="text-xs text-stone-500">{label}</p><p className="mt-2 break-words text-lg font-medium tabular-nums">{money(value===null?null:Number(value))}</p></div>)}</div><p className={`mb-4 rounded-lg p-4 text-sm ${data.readyForFinalReview?"bg-emerald-50 text-emerald-900":"bg-amber-50 text-amber-900"}`}>{data.readyForFinalReview?"Recorded finances and checked source documents are ready for final review.":`${data.items.length} items need attention before final review.`} This checklist does not close the project or reconcile your bank account.</p><h4 className="mb-3 font-medium">Items to resolve ({data.items.length})</h4><div className="divide-y divide-stone-200 rounded-lg border border-stone-200 bg-white">{data.items.map(item=><button key={item.key} className="block w-full px-4 py-3 text-left hover:bg-stone-50" onClick={()=>onView(item.view)}><p className="text-sm font-medium">{item.label}</p><p className="mt-1 text-xs text-stone-500">{item.detail}</p></button>)}</div><p className="mt-4 text-xs text-stone-500">Checked {new Date(data.checkedAt).toLocaleString("en-GB")} · {data.drive.scannedFiles} Drive files scanned · {data.drive.complete?"Folder scan complete":"Drive check incomplete"}. Expected profit uses the approved estimate and current cost forecast. Changes outside the app require another check. Currency conversion and bank reconciliation need separate review.</p></>}</div>;
}
