import type { FxValue } from "./FxFields";
import { useEffect, useState, type FormEvent } from "react";
export type PoCost = {fx?:FxValue|null;id:string;description:string;supplier:string;supplierKey:string;committedMinor:number;activePurchaseOrderId?:string|null};
export type FinancePo = {currency:string;cancellationReason:string|null;id:string;poNumber:string;supplierName:string;supplierEmail:string|null;supplierTerms:string|null;notes:string|null;status:string;version:number;totalMinor:number;invoicedMinor:number;remainingMinor:number;documentStatus:string;documentError:string|null;issuedAt:string|null;financeLines:{sourceNetMinor?:number|null;costId:string;description:string;netMinor:number}[];pdfJobFile:{id:string;driveSyncStatus:string;driveSyncError:string|null;driveWebViewLink:string|null}|null};
const button="inline-flex min-h-10 items-center justify-center rounded-md border border-stone-200 bg-white px-3 py-2 text-sm hover:bg-stone-50 disabled:opacity-40";
const primary=`${button} !bg-stone-900 !text-white`;
const input="mt-1 w-full rounded-md border border-stone-300 bg-white px-3 py-2 text-sm";
const decimal=(value:number)=>(value/100).toFixed(2);
export default function PurchaseOrderPanel({productionId,currency,costs,orders,busy,onSave,requestError,requestedCostId,onRequestedCostHandled}:{productionId:string;currency:string;costs:PoCost[];orders:FinancePo[];busy:boolean;requestError:string;onSave:(action:string,body:Record<string,unknown>)=>Promise<boolean>;requestedCostId?:string;onRequestedCostHandled:()=>void}) {
 const [editor,setEditor]=useState<{po?:FinancePo;costId?:string}>();const [confirm,setConfirm]=useState<{po:FinancePo;action:"issue"|"cancel"}>();const [reason,setReason]=useState("");const [dialogError,setDialogError]=useState("");
 const money=(value:number)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(value/100);
 useEffect(()=>{if(requestedCostId){setEditor({costId:requestedCostId});onRequestedCostHandled();}},[requestedCostId,onRequestedCostHandled]);
 async function action(){if(!confirm)return;const ok=await onSave(`po.${confirm.action}`,{id:confirm.po.id,version:confirm.po.version,...(confirm.action==="cancel"?{reason}:{})});if(ok){setConfirm(undefined);setReason("");setDialogError("");}else setDialogError("Could not complete the change. Close this dialog to review the error above, then refresh the records if needed.");}
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="font-medium">Supplier purchase orders</h4><p className="mt-1 max-w-2xl text-sm text-stone-500">Select live costs for one supplier, review the agreement, then issue a frozen PO. Its PDF is filed to the project’s supplier contracts folder.</p></div><button className={primary} disabled={busy||!costs.some(c=>!c.activePurchaseOrderId&&c.supplierKey!=="unassigned")} onClick={()=>setEditor({})}>New purchase order</button></div>
 {!orders.length&&<p className="rounded-lg border border-dashed border-stone-300 p-6 text-sm text-stone-500">No purchase orders yet. Assign a supplier to a live cost, then create a PO here.</p>}
 {orders.map(po=><article className="rounded-lg border border-stone-200 bg-white p-4" key={po.id}><div className="flex flex-wrap justify-between gap-3"><div><h5 className="font-medium">{po.poNumber} · {po.supplierName}</h5><p className="mt-1 text-xs text-stone-500">{po.status.toLowerCase()}{po.issuedAt&&` · Issued ${po.issuedAt.slice(0,10)}`} · {po.financeLines.length} cost{po.financeLines.length===1?"":"s"}</p></div><div className="text-right"><p className="font-medium">{money(po.totalMinor)} net</p>{po.currency!==currency&&<p className="text-xs">Supplier agreement: {new Intl.NumberFormat("en-GB",{style:"currency",currency:po.currency}).format(po.financeLines.reduce((s,l)=>s+(l.sourceNetMinor??l.netMinor),0)/100)}</p>}{po.status==="ISSUED"&&<p className={`mt-1 text-xs ${po.invoicedMinor>po.totalMinor?"text-red-700":"text-stone-500"}`}>{money(po.invoicedMinor)} invoiced · {money(po.remainingMinor)} unbilled</p>}</div></div>
 <details className="mt-3 text-sm"><summary className="cursor-pointer text-stone-600">Agreed costs & scope</summary><ul className="mt-2 space-y-2">{po.financeLines.map(l=><li className="flex justify-between gap-3" key={l.costId}><span>{l.description}</span><span>{money(l.netMinor)}</span></li>)}</ul>{po.notes&&<p className="mt-3 whitespace-pre-wrap">{po.notes}</p>}{po.supplierTerms&&<p className="mt-3 whitespace-pre-wrap text-stone-500">{po.supplierTerms}</p>}</details>
 <div className="mt-4 flex flex-wrap gap-2">{po.status==="DRAFT"&&<><button className={button} disabled={busy} onClick={()=>setEditor({po})}>Edit draft</button><a className={button} href={`/api/project-finance/${productionId}/purchase-orders/${po.id}/preview`} target="_blank" rel="noreferrer">Preview PDF</a><button className={primary} disabled={busy} onClick={()=>{setDialogError("");setConfirm({po,action:"issue"});}}>Issue PO</button></>}{po.pdfJobFile&&<><a className={button} href={`/api/files/${po.pdfJobFile.id}/download`} target="_blank" rel="noreferrer">{po.status==="CANCELLED"?"Original issued PDF":"Download PO"}</a>{po.pdfJobFile.driveWebViewLink&&<a className={button} href={po.pdfJobFile.driveWebViewLink} target="_blank" rel="noreferrer">Open in Drive</a>}</>}{["DRAFT","ISSUED"].includes(po.status)&&<button className={button} disabled={busy} onClick={()=>{setReason("");setDialogError("");setConfirm({po,action:"cancel"});}}>Cancel PO</button>}{po.documentStatus==="ERROR"&&<button className={button} disabled={busy} onClick={()=>onSave("po.retry-document",{id:po.id,version:po.version})}>Retry PDF</button>}</div>
 {po.documentStatus==="PENDING"&&<p role="status" className="mt-3 text-xs text-stone-500">Preparing the issued PDF… Refresh to check progress.</p>}{po.documentError&&<p className="mt-3 text-xs text-red-700">{po.documentError}</p>}{po.pdfJobFile&&po.pdfJobFile.driveSyncStatus!=="SYNCED"&&<p className="mt-3 text-xs text-stone-500">{po.pdfJobFile.driveSyncStatus==="ERROR"?po.pdfJobFile.driveSyncError:po.pdfJobFile.driveSyncStatus==="LOCAL"?"PDF saved locally. Set up the project Drive folder and publish it from Files.":"PDF ready · queued for Google Drive."} <a className="underline" href={`/productions?production=${productionId}&tab=Files`}>Files & publishing</a></p>}{po.status==="CANCELLED"&&<p className="mt-3 text-xs text-amber-800">Cancelled{po.cancellationReason?`: ${po.cancellationReason}`:""}. Any issued PDF is retained as history; do not use it for a new booking.</p>}</article>)}
 {editor&&<PoEditor key={editor.po?.id||editor.costId||"new"} costs={costs} po={editor.po} costId={editor.costId} currency={currency} busy={busy} requestError={requestError} onClose={()=>setEditor(undefined)} onSave={async(body)=>{const ok=await onSave(editor.po?"po.update":"po.create",body);if(ok)setEditor(undefined);return ok;}}/>}
 {confirm&&<div className="fixed inset-0 z-[800] grid place-items-center bg-black/30 p-4"><section role="dialog" aria-modal="true" aria-label={confirm.action==="issue"?"Issue purchase order":"Cancel purchase order"} className="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><h3 className="text-lg font-medium">{confirm.action==="issue"?"Issue purchase order":"Cancel purchase order"}</h3><p className="mt-3 text-sm text-stone-600">{confirm.po.poNumber} · {confirm.po.supplierName} · {money(confirm.po.totalMinor)} net</p><p className="mt-3 text-sm text-stone-600">{confirm.action==="issue"?"This freezes the supplier agreement, sets the selected costs to the agreed commitments, and creates its PDF for Drive. It does not send an email.":confirm.po.status==="DRAFT"?"This releases the selected costs from the draft. The draft and its history remain available.":"This returns the costs to planned allowances and retains their forecast. Costs with active invoice allocations must be corrected first. The original issued PDF stays in the history."}</p>{confirm.action==="cancel"&&<label className="mt-4 block text-sm">Cancellation reason<textarea className={input} required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}{(requestError||dialogError)&&<p role="alert" className="mt-3 text-sm text-red-700">{requestError||dialogError}</p>}<div className="mt-5 flex justify-end gap-2"><button className={button} disabled={busy} onClick={()=>setConfirm(undefined)}>Back</button><button className={primary} disabled={busy||(confirm.action==="cancel"&&!reason.trim())} onClick={action}>{busy?"Saving…":confirm.action==="issue"?"Confirm issue":"Confirm cancellation"}</button></div></section></div>}
 </div>;
}
function PoEditor({costs,po,costId,currency,busy,requestError,onClose,onSave}:{costs:PoCost[];po?:FinancePo;costId?:string;currency:string;busy:boolean;requestError:string;onClose:()=>void;onSave:(body:Record<string,unknown>)=>Promise<boolean>}) {
 const available=costs.filter(c=>(!c.activePurchaseOrderId||c.activePurchaseOrderId===po?.id)&&c.supplierKey!=="unassigned");
 const first=costId?available.find(c=>c.id===costId):available.find(c=>po?.financeLines.some(l=>l.costId===c.id))||available[0];
 const [supplier,setSupplier]=useState(first?.supplierKey||"");const [selected,setSelected]=useState<Record<string,string>>(po?Object.fromEntries(po.financeLines.map(l=>[l.costId,decimal(l.sourceNetMinor??l.netMinor)])):costId&&first?{[costId]:decimal(first.fx?.netMinor??first.committedMinor)}:{});
 const [email,setEmail]=useState(po?.supplierEmail||"");const [scope,setScope]=useState(po?.notes||"");const [terms,setTerms]=useState(po?.supplierTerms||"");const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setError("");const ok=await onSave({id:po?.id,version:po?.version,supplierEmail:email,notes:scope,supplierTerms:terms,lines:Object.entries(selected).map(([id,net])=>({costId:id,net}))});if(!ok)setError("Could not save the PO. Close this dialog to review the error above, then refresh if another change was made.");}
 return <div className="fixed inset-0 z-[800] flex justify-end bg-black/30"><section role="dialog" aria-modal="true" aria-label={po?"Edit purchase order":"New purchase order"} className="flex h-full w-full max-w-xl flex-col bg-white shadow-xl"><div className="flex items-center justify-between border-b border-stone-200 p-5"><h3 className="text-lg font-medium">{po?`Edit ${po.poNumber}`:"New purchase order"}</h3><button className={button} disabled={busy} onClick={onClose}>Close</button></div><form className="flex min-h-0 flex-1 flex-col" onSubmit={submit}><div className="flex-1 space-y-4 overflow-y-auto p-5">{(requestError||error)&&<p role="alert" className="text-sm text-red-700">{requestError||error}</p>}<label className="block text-sm">Supplier<select className={input} value={supplier} disabled={Boolean(po)||busy} onChange={e=>{setSupplier(e.target.value);setSelected({});}}>{[...new Map(available.map(c=>[c.supplierKey,c.supplier])).entries()].map(([key,name])=><option value={key} key={key}>{name}</option>)}</select></label><p className="text-xs text-stone-500">Select costs and confirm the agreed net amounts. Drafts reserve these costs; issuing the PO replaces their allowances with the agreed commitments.</p>
 {available.filter(c=>c.supplierKey===supplier&&(!po||po.financeLines.some(l=>l.costId===c.id))).map(c=><div className="rounded-lg border border-stone-200 p-3" key={c.id}><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={c.id in selected} disabled={Boolean(po)||busy} onChange={e=>{const next={...selected};if(e.target.checked)next[c.id]=decimal(c.fx?.netMinor??c.committedMinor);else delete next[c.id];setSelected(next);}}/>{c.description}</label>{c.id in selected&&<label className="mt-2 block text-xs text-stone-500">Agreed net — {c.description} ({c.fx?.currency||currency})<input className={input} required inputMode="decimal" value={selected[c.id]} onChange={e=>setSelected({...selected,[c.id]:e.target.value})}/></label>}</div>)}
 <label className="block text-sm">Supplier email (optional)<input className={input} type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm">Supplier-facing scope<textarea className={`${input} min-h-28`} maxLength={4000} value={scope} onChange={e=>setScope(e.target.value)}/></label><label className="block text-sm">Supplier-facing terms<textarea className={`${input} min-h-24`} maxLength={2000} value={terms} onChange={e=>setTerms(e.target.value)}/></label><p className="text-xs text-stone-500">These notes appear on the supplier PDF. Internal project and estimate notes are excluded. No email is sent from this form.</p></div><div className="flex justify-end gap-2 border-t border-stone-200 p-5"><button type="button" className={button} disabled={busy} onClick={onClose}>Cancel</button><button className={primary} disabled={busy||!Object.keys(selected).length}>{busy?"Saving…":"Save PO draft"}</button></div></form></section></div>;
}
