ALTER TYPE "ProductionStatus" ADD VALUE IF NOT EXISTS 'PRE_PRO';
ALTER TYPE "ProductionStatus" ADD VALUE IF NOT EXISTS 'SHOOT';
ALTER TYPE "ProductionStatus" ADD VALUE IF NOT EXISTS 'POST';
ALTER TYPE "ProductionStatus" ADD VALUE IF NOT EXISTS 'WRAPPED';
